CREATE TABLE IF NOT EXISTS Employees(
	EmployeeID INT(6) AUTO_INCREMENT PRIMARY KEY,
	LastName VARCHAR(255) NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	Title VARCHAR(255),
	TitleOfCourtesy VARCHAR(255),
	BirthDate DATE, 
	HireDate DATE,
	Address VARCHAR(255) NOT NULL,
	City VARCHAR(255) NOT NULL
);